[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.17"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@erc3643/contracts/=lib/erc3643/contracts/",
    "@onchain-id/solidity/=lib/solidity/",
    "forge-std/=lib/forge-std/src/"
]

via_ir = true
optimizer = true
optimizer_runs = 200

# 禁用验证
verify = false
[rpc_endpoints]
pharos = "https://devnet.dplabs-internal.com/"

[etherscan]
pharos = { key = "${ETHERSCAN_API_KEY}", url = "https://pharos.explorer.dplabs-internal.com/api" }

